config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Defines the root path route ("/")
# root "articles#index"

Rails.application.routes.draw do

  # GET /route_name in [controller_file_name#method_name]

  get "about-frontend-thingy", to: "about#index", as: :about

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  
  delete "logout", to: "sessions#destroy"

  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"
  
  resources :twitter_accounts
  # get "twitter_accounts/:id"
  # delete "twitter_accounts/:id"

  # alternate to root: get "/"
  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user

  # prevent duplicate in username
  validates :username, uniqueness: true
end

app/models/user.rb
# email:string
# password_digest:string
#
# password:string virtual
# password_confirmation:string virtual

class User < ApplicationRecord
  has_many :twitter_accounts # association with twitter account
  has_secure_password # rails feature that gives us that .authenticate() method

  validates :email, presence: true, format: {
    with: /\A[^@\s]+@[^@\s]+\z/,
    message: "must be a valid email"
  }
end

app/controllers/about_controller.rb
# needs to match the file name and remove the underscore

# inherit from Application controller
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  
  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end
  
  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # flash.now[:notice] = "Logged in successfully."
    # flash.now[:alert] = "Invalid email or password"
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def twitter
    # render plain: "Successfully logged in"

    Rails.logger.info twitter_auth

    # check duplicate
    # update account if existing
    twitter_account = Current.user.twitter_accounts.where(username: twitter_auth.info.nickname).first_or_initialize
    twitter_account.update(
      name: twitter_auth.info.name,
      image: twitter_auth.info.image,
      token: twitter_auth.credentials.token,
      secret: twitter_auth.credentials.secret,
    )

    redirect_to twitter_accounts_path, notice: "Successfully connected your account"
  end

  # give hash of credentials back from twitter
  def twitter_auth
    request.env['omniauth.auth']
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      # go to password  mailer
      # send reset email but we want to include where to send
      # this will set up "params" in mailer
      # call deliver_later as a background job
      # since it takes a while to connect
      # similar to synchronous in JS

      # deliver_now = async
      # deliver_later = sync
      PasswordMailer.with(user: @user).reset.deliver_later  
    else
      render :new
    end
    redirect_to root_path, notice: "Check your email for the reset password link"
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")

  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: "Your token has expired"
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to root_path, notice: "Your password was reset successfully."
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit
    
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password updated!"
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    # # {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"randomemail@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign Up"}
    # params
    # # {"email"=>"randomemail@gmail.com", "password"=>"password", "password_confirmation"=>"password"}
    # params[:user]
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully created account"      
    else
      # flash[:alert] = "Something was wrong"
      render :new
    end
    # render plain: @user.save ? "Success!" : "Failed"
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    # if @user
      session[:user_id] = nil
      redirect_to root_path, notice: "Logged out"
    # end
  end
end

app/controllers/twitter_accounts_controller.rb
# rails credentials:edit --environment=development

class TwitterAccountsController < ApplicationController
  before_action :require_user_logged_in!

  def index
    # if Current.user
    #   @twitter_accounts = Current.user.twitter_accounts
    # else
    #   redirect_to root_path
    # end
   
    @twitter_accounts = Current.user.twitter_accounts
  end

  def destroy
    @twitter_account = Current.user.twitter_accounts.find(params[:id])

    @twitter_account.destroy
    
    redirect_to twitter_accounts_path, alert: "Successfully disconnected @#{@twitter_account.username}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1>About Us</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1>Welcome to Scheduled Tweets</h1>
</div>

<%= button_to "Connect Twitter", "/auth/twitter", method: :post, class: "btn btn-primary" %>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
  <% if form.object.errors.any? %>
    <%= form.object.errors.full_messages.each do |message| %>
      <div class="alert alert-danger">
        <div><%= message %></div>
      </div>
    <% end %>
  <% end %>
  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control", placeholder: "New password" %>
  </div>
  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm new password" %>
  </div>
  <div class="mb-3">
    <%= form.submit "Reset password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with url: password_reset_path do |form| %>
  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "abby@gmail.com"  %>
  </div>
  <div class="mb-3">
    <%= form.submit "Reset password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Icon", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", about_path, class: "nav-link" %>
        </li>
        <% if Current.user && Current.user.id != nil %>
          <li class="nav-item">
            <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
          </li>
          <li>
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
          </li>
        <% else %>
          <%= link_to "Login", sign_in_path, class: "nav-link" %>
          <%= link_to "Register", sign_up_path, class: "nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/twitter_accounts/index.html.erb
<div class="container">
  <div class="d-flex align-items-center justify-content-between mb-4">
    <h1>Twitter accounts</h1>
    <%= button_to "Connect a Twitter account", "/auth/twitter", method: :post, class: "btn btn-primary" %>
  </div>

  <% @twitter_accounts.each do |twitter_account| %>
    <div class="d-flex align-items-center mb-4">
      <%= image_tag twitter_account.image, class: "rounded-circle" %>
      <%= link_to "@#{twitter_account.username}", "https://www.twitter.com/#{twitter_account.username}", target: :_blank %>
      <%= button_to "Disconnect", twitter_account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    </div>
  <% end %>
</div>